services:
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    ports:
      - 4949:80
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 123
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MARIADB_DATABASE: wali
      MARIADB_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
